<?php
echo '<u>Dettask.php</u>';
echo '<br />';
echo 'Edit CODTYPT';
echo '<br />';
echo 'Edit Destinataires';
echo '<br />';
echo 'Edit Affectations';
echo '<br />';
echo 'Edit Priorit&eacute;';
echo '<br />';
echo 'Edit &Eacute;ch&eacute;ance';
echo '<br />';
echo 'Ajout commentaires';
echo '<br />';
echo 'Edit URGTASK';
echo '<br />';
echo 'Edit Sp&eacute;cif info';
echo '<br />';
echo 'Edit Statut';
echo '<br />';
echo 'Edit Appli';
echo '<br />';
echo 'Edit Patch';
echo '<br /><br />';
echo '<u>Gettypc.php</u>';
echo '<br />';
echo 'Edit statut priv&eacute;';
echo '<br /><br />';
echo '<u>Queries.php</u>';
echo '<br />';
echo 'Ajout loadPage(\'connect/deconnect.php\') lors de connexion/deconnexion';
echo '<br /><br />';
echo '<u>Listtask.php</u>';
echo '<br />';
echo 'Ajout tris et filtres';
echo '<br />';
echo 'Ajout choix des colonnes';
?>